"""restructure_perimeter_departments

Revision ID: 20ba06586d52
Revises: d9292f775855
Create Date: 2026-01-04 17:33:10.304198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ba06586d52'
down_revision: Union[str, Sequence[str], None] = 'd9292f775855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop the old pk primary key constraint
    op.drop_constraint('perimeters_pkey', 'perimeters', type_='primary')
    
    # Drop the old constraints and columns from perimeters
    op.drop_constraint(op.f('perimeters_department_id_fkey'), 'perimeters', type_='foreignkey')
    op.drop_column('perimeters', 'department_id')
    op.drop_column('perimeters', 'pk')
    
    # Add primary key constraint on id column
    op.create_primary_key('perimeters_pkey', 'perimeters', ['id'])
    
    # Now create the perimeter_departments table
    op.create_table('perimeter_departments',
    sa.Column('perimeter_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['perimeter_id'], ['perimeters.id'], ),
    sa.PrimaryKeyConstraint('perimeter_id', 'department_id')
    )
    
    # Finally, create the acls table
    op.create_table('acls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('perimeter_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['perimeter_id'], ['perimeters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perimeters', sa.Column('pk', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('perimeters', sa.Column('department_id', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('perimeters_department_id_fkey'), 'perimeters', 'departments', ['department_id'], ['id'])
    op.alter_column('perimeters', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_table('perimeter_departments')
    op.drop_table('acls')
    # ### end Alembic commands ###
