"""Moved csv files and added PK to perimeter table

Revision ID: 52e991b23f4d
Revises: 07087f086ade
Create Date: 2026-01-04 17:15:05.663048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e991b23f4d'
down_revision: Union[str, Sequence[str], None] = '07087f086ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if perimeters table exists, if not recreate it
    # This handles cases where tables were manually dropped
    from sqlalchemy import inspect
    inspector = inspect(op.get_bind())
    
    if 'perimeters' not in inspector.get_table_names():
        # Recreate perimeters table with pk column
        op.create_table('perimeters',
            sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('id', sa.Integer(), nullable=True),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('department_id', sa.Float(), nullable=False),
            sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
            sa.PrimaryKeyConstraint('pk')
        )
    else:
        # Table exists, just add the new column
        op.add_column('perimeters', sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False))
        op.alter_column('perimeters', 'id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    
    # Recreate acls table if it doesn't exist
    if 'acls' not in inspector.get_table_names():
        op.create_table('acls',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('user_id', sa.String(length=255), nullable=False),
            sa.Column('perimeter_id', sa.Integer(), nullable=True),
            sa.Column('department_id', sa.Float(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
            sa.ForeignKeyConstraint(['perimeter_id'], ['perimeters.pk'], ),
            sa.PrimaryKeyConstraint('id')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('perimeters', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('perimeters', 'pk')
    # ### end Alembic commands ###
