"""modified_acl_id_column

Revision ID: f89151b9118e
Revises: dcb14d4c921b
Create Date: 2026-01-05 22:58:58.240322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89151b9118e'
down_revision = 'dcb14d4c921b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE acls ALTER COLUMN id TYPE INTEGER USING (id::text::integer)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('acls', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
